### ISSUE TITLE
杜卡币来源

### ISSUE THREAD

**Issue by KingPrimes** [KingPrimes/ZeroKingBot#11]
杜卡币
---
---
杜卡币通过模拟开核桃兑换
通过 
- QQ号 绑定用户
- QQ昵称 显示名称
- Prime物品名称
- 物品个数

模拟开核桃
---
---
修改模拟开核桃规则
- 模拟开核桃可以与玩家组队，不再是随机。
- 模拟开核桃需要选择自身拥有的核桃。

**Comment by fbbDirge** [comment]
什么时候提上日程
