### ISSUE TITLE
增加紫卡评分功能

### ISSUE THREAD

**Issue by coolingziyu** [KingPrimes/ZeroKingBot#24]
举例
![IMG20220904173010](https://user-images.githubusercontent.com/108464016/188306908-ba44c725-7748-46a9-8b61-1993dc172dc3.jpg)

**Comment by coolingziyu** [comment]
可以拉去极镜数据

**Comment by KingPrimes** [comment]
已更新位于：
- 987fdeed: Warframe紫卡分析
