### ISSUE TITLE
请求添加查看钢铁裂隙的功能

### ISSUE THREAD

**Issue by JoMo16** [KingPrimes/ZeroKingBot#25]
钢铁裂隙和普通裂隙不一样，请求添加功能

**Comment by KingPrimes** [comment]
好的👌🏻



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月14日 23:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [KingPrimes/ZeroKingBot] 请求添加查看钢铁裂隙的功能 (Issue #25) |

钢铁裂隙和普通裂隙不一样，请求添加功能

**Comment by KingPrimes** [comment]
* 提交于 - eb451ba4
* 以分类裂隙，裂隙、九重天裂隙、钢铁裂隙。
