### ISSUE TITLE
本机配置时登录显示密码错误或账号冻结

### ISSUE THREAD

**Issue by sllnull** [KingPrimes/ZeroKingBot#33]
[sys-error.log](https://github.com/KingPrimes/ZeroKingBot/files/11087081/sys-error.log)
[sys-info.log](https://github.com/KingPrimes/ZeroKingBot/files/11087082/sys-info.log)
![}~G% HM(YMDBS}(S1(23 DL](https://user-images.githubusercontent.com/60806759/228175993-10f469f6-acf7-4865-9a9c-bf78f5e5771e.png)

**Comment by Ronronner-j** [comment]
你将device.json的“protocol”：5改成2，再登录。如果还不行，要求你同一网络下验证的话，你就在本地登录后再整个文件复制到服务器
