### ISSUE TITLE
你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。

### ISSUE THREAD

**Issue by lihuaxue** [KingPrimes/ZeroKingBot#38]
![2f69d55b0908b80c9e85244eb25b4201](https://github.com/KingPrimes/ZeroKingBot/assets/138700658/7ee66652-af40-4715-9b4d-42fc4d8cd781)
[sys-error.log](https://github.com/KingPrimes/ZeroKingBot/files/11990655/sys-error.log)
[sys-info.log](https://github.com/KingPrimes/ZeroKingBot/files/11990656/sys-info.log)

**Comment by KingPrimes** [comment]
请到https://github.com/Mrs4s/go-cqhttp这里查看提问
