### ISSUE TITLE
无法回复对话

### ISSUE THREAD

**Issue by jiuyannb** [KingPrimes/ZeroKingBot#40]
#### 附加信息
*如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。*
[zero-king-bot-logs.zip](https://github.com/KingPrimes/ZeroKingBot/files/13832051/zero-king-bot-logs.zip)
![image](https://github.com/KingPrimes/ZeroKingBot/assets/154609851/f5fdc8ca-d8a8-40f6-b6ef-ff9b3b2eccdb)

**Comment by KingPrimes** [comment]
已于 2164d2f0 修复
